phraseapp:
  access_token: 73745aeeb6aa7fdcb0ce407f55e8e406bf41d5252896af3b21cb0b0e8e325e13
  project_id: 8c7dcc8b8b584c68e5ab26ccb1a5d47b
  file_format: json
  push:
    sources:
      - file: "./widget/*.json"
  pull:
    targets:
      - file: "./widget/<locale_code>.json"
